--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ImJustNozell/YamlProvider
build-by-default: true
branches:
- main
projects:
  YamlProvider:
    path: ""
    model: virion
    type: library
...
